name: The Carrs
favicon: null
layout_spectrum: 0.7561
typography_spectrum: 0.271
title: "Our little place n the 'Net"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b0b'
    - '#256897'
    - '#034271'
    - '#02440b'
    - '#125c23'
  brandStrength: 0.3125
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
