name: The Carrs
favicon: null
layout_spectrum: 0.51516
typography_spectrum: 0.34327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#262161'
    - '#565658'
    - '#adadae'
    - '#228fce'
  brandStrength: 0.3125
  lightness: 0.9811882071662694
  saturation: 0.25
  rhythmicContrast: 0.15779849607497454
purpose: []
